{"name": "Traceroute к 192.168.42.2", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.42.2 не достигнута\nassert False", "trace": "ce_ip = '192.168.42.2'\n\n    @allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Traceroute тестирование\")\n    @allure.title(\"Traceroute к CE устройствам\")\n    @allure.description(\"Тестирование маршрута до CE устройств через VLAN\")\n    @pytest.mark.parametrize(\"ce_ip\", IP_DST)\n    def test_traceroute_to_ce(ce_ip):\n    \n        allure.dynamic.title(f\"Traceroute к {ce_ip}\")\n        allure.dynamic.description(f\"Проверка маршрута до устройства {ce_ip}\")\n    \n        with allure.step(\"Запуск traceroute\"):\n            hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n    \n        # Проверка достижения цели\n        with allure.step(\"Проверка достижения цели\"):\n>           assert reached_destination, f\"Цель {ce_ip} не достигнута\"\nE           AssertionError: Цель 192.168.42.2 не достигнута\nE           assert False\n\ntest_traceroute.py:128: AssertionError"}, "description": "Проверка маршрута до устройства 192.168.42.2", "steps": [{"name": "Запуск traceroute", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.42.2'", "status": "passed", "steps": [{"name": "Traceroute к 192.168.42.2", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "9e4773fe-4248-4c63-b052-36d9045ce901-attachment.attach"}], "start": 1755749982360, "stop": 1755749982360}, {"name": "Хоп 1", "status": "passed", "attachments": [{"name": "Хоп 1 детали", "source": "836af4ec-275f-43a0-af74-4cb7ed254001-attachment.attach"}], "start": 1755749982360, "stop": 1755749982387}, {"name": "Хоп 2", "status": "passed", "attachments": [{"name": "Хоп 2 детали", "source": "04cb066c-c9be-4c8c-8ece-6859221be567-attachment.attach"}], "start": 1755749982387, "stop": 1755749982409}], "parameters": [{"name": "dst_ip", "value": "'192.168.42.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755749982360, "stop": 1755749982409}], "start": 1755749982360, "stop": 1755749982409}, {"name": "Проверка достижения цели", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.42.2 не достигнута\nassert False\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 128, in test_traceroute_to_ce\n    assert reached_destination, f\"Цель {ce_ip} не достигнута\"\n"}, "start": 1755749982409, "stop": 1755749982409}], "parameters": [{"name": "ce_ip", "value": "'192.168.42.2'"}], "start": 1755749982360, "stop": 1755749982410, "uuid": "46d05db8-1ee1-47b3-8790-92ea905f953e", "historyId": "6ebd27b58705b0f3c79aacfd0febe32a", "testCaseId": "430986e6801dc82aa72d8850714fa921", "fullName": "test_traceroute#test_traceroute_to_ce", "labels": [{"name": "feature", "value": "Traceroute тестирование"}, {"name": "epic", "value": "Сетевые тесты"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "20348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}