{"name": "Traceroute к 192.168.43.2", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'", "trace": "ce_ip = '192.168.43.2'\n\n    @allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Traceroute тестирование\")\n    @allure.title(\"Traceroute к CE устройствам\")\n    @allure.description(\"Тестирование маршрута до CE устройств через VLAN\")\n    @pytest.mark.parametrize(\"ce_ip\", IP_DST)\n    def test_traceroute_to_ce(ce_ip):\n    \n        allure.dynamic.title(f\"Traceroute к {ce_ip}\")\n        allure.dynamic.description(f\"Проверка маршрута до устройства {ce_ip}\")\n    \n        with allure.step(\"Запуск traceroute\"):\n>           hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntest_traceroute.py:163: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_traceroute.py:85: in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n../../venv/lib/python3.12/site-packages/allure_commons/_allure.py:210: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n../../venv/lib/python3.12/site-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../venv/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../venv/lib/python3.12/site-packages/allure_pytest/listener.py:254: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n../../venv/lib/python3.12/site-packages/allure_commons/reporter.py:165: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n../../venv/lib/python3.12/site-packages/pluggy/_hooks.py:512: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../venv/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x78d7fcc74e00>, body = None, file_name = 'b12e6f5b-e0f2-4c79-b29e-978e5960d0b2-attachment.txt'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = self._report_dir / file_name\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, str):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\n../../venv/lib/python3.12/site-packages/allure_commons/logger.py:48: TypeError"}, "description": "Проверка маршрута до устройства 192.168.43.2", "steps": [{"name": "Запуск traceroute", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 163, in test_traceroute_to_ce\n    hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "Выполнение traceroute к '192.168.43.2'", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "Traceroute к 192.168.43.2", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "Ошибка диаграммы", "source": "aa927128-d0ae-43b6-83b5-b2c290b4df8d-attachment.attach"}, {"name": "Схема ожидаемого маршрута", "source": "b12e6f5b-e0f2-4c79-b29e-978e5960d0b2-attachment.txt", "type": "text/plain"}], "start": 1755749539564, "stop": 1755749539564}], "parameters": [{"name": "dst_ip", "value": "'192.168.43.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755749539564, "stop": 1755749539566}], "start": 1755749539564, "stop": 1755749539566}], "attachments": [{"name": "stdout", "source": "e546cc21-33d0-44b2-8f42-e5ecb41ea92f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "ce_ip", "value": "'192.168.43.2'"}], "start": 1755749539564, "stop": 1755749539567, "uuid": "987125d1-4408-41ef-bf4e-6d9988249eea", "historyId": "2299e8c537bf1def73fd98e543964c15", "testCaseId": "430986e6801dc82aa72d8850714fa921", "fullName": "test_traceroute#test_traceroute_to_ce", "labels": [{"name": "epic", "value": "Сетевые тесты"}, {"name": "feature", "value": "Traceroute тестирование"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "19500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}