{"name": "Traceroute к 192.168.42.2", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.42.2 не достигнута\nassert False", "trace": "ce_ip = '192.168.42.2'\n\n    @allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Traceroute тестирование\")\n    @allure.title(\"Traceroute к CE устройствам\")\n    @allure.description(\"Тестирование маршрута до CE устройств через VLAN\")\n    @pytest.mark.parametrize(\"ce_ip\", IP_DST)\n    def test_traceroute_to_ce(ce_ip):\n    \n        allure.dynamic.title(f\"Traceroute к {ce_ip}\")\n        allure.dynamic.description(f\"Проверка маршрута до устройства {ce_ip}\")\n    \n        with allure.step(\"Запуск traceroute\"):\n            hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n    \n        # Проверка достижения цели\n        with allure.step(\"Проверка достижения цели\"):\n>           assert reached_destination, f\"Цель {ce_ip} не достигнута\"\nE           AssertionError: Цель 192.168.42.2 не достигнута\nE           assert False\n\ntest_traceroute.py:128: AssertionError"}, "description": "Проверка маршрута до устройства 192.168.42.2", "steps": [{"name": "Запуск traceroute", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.42.2'", "status": "passed", "steps": [{"name": "Traceroute к 192.168.42.2 через VLAN 4028", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "0b93e98e-514c-4938-ba7c-6cd76a11a85e-attachment.attach"}], "start": 1755747495337, "stop": 1755747495337}, {"name": "Хоп 1", "status": "passed", "attachments": [{"name": "Хоп 1 детали", "source": "aaa8f6f5-497e-469a-85d6-0315ac26d231-attachment.attach"}], "start": 1755747495337, "stop": 1755747495359}, {"name": "Хоп 2", "status": "passed", "attachments": [{"name": "Хоп 2 детали", "source": "919c76a7-3cd3-4e4e-ad81-b54d1ef62d0a-attachment.attach"}], "start": 1755747495359, "stop": 1755747495378}], "parameters": [{"name": "dst_ip", "value": "'192.168.42.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755747495337, "stop": 1755747495378}], "start": 1755747495337, "stop": 1755747495378}, {"name": "Проверка достижения цели", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.42.2 не достигнута\nassert False\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 128, in test_traceroute_to_ce\n    assert reached_destination, f\"Цель {ce_ip} не достигнута\"\n"}, "start": 1755747495378, "stop": 1755747495378}], "parameters": [{"name": "ce_ip", "value": "'192.168.42.2'"}], "start": 1755747495337, "stop": 1755747495379, "uuid": "9c883ed2-302a-436c-89bb-b346457a55c6", "historyId": "6ebd27b58705b0f3c79aacfd0febe32a", "testCaseId": "430986e6801dc82aa72d8850714fa921", "fullName": "test_traceroute#test_traceroute_to_ce", "labels": [{"name": "epic", "value": "Сетевые тесты"}, {"name": "feature", "value": "Traceroute тестирование"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "14900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}