{"name": "Traceroute к 192.168.43.2", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.43.2 не достигнута\nassert False", "trace": "ce_ip = '192.168.43.2'\n\n    @allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Traceroute тестирование\")\n    @allure.title(\"Traceroute к CE устройствам\")\n    @allure.description(\"Тестирование маршрута до CE устройств через VLAN\")\n    @pytest.mark.parametrize(\"ce_ip\", IP_DST)\n    def test_traceroute_to_ce(ce_ip):\n        \"\"\"Тест traceroute с проверкой маршрута до CE устройств\"\"\"\n    \n        allure.dynamic.title(f\"Traceroute к {ce_ip}\")\n        allure.dynamic.description(f\"Проверка маршрута до устройства {ce_ip}\")\n    \n        with allure.step(\"Запуск traceroute\"):\n            hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n    \n        # Проверка достижения цели\n        with allure.step(\"Проверка достижения цели\"):\n>           assert reached_destination, f\"Цель {ce_ip} не достигнута\"\nE           AssertionError: Цель 192.168.43.2 не достигнута\nE           assert False\n\ntest_traceroute.py:130: AssertionError"}, "description": "Проверка маршрута до устройства 192.168.43.2", "steps": [{"name": "Запуск traceroute", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.43.2'", "status": "passed", "steps": [{"name": "Traceroute к 192.168.43.2 через VLAN 4028", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "f58007e1-c3af-4e92-9937-e5bd78aa05a1-attachment.attach"}], "start": 1755742103195, "stop": 1755742103195}, {"name": "Хоп 1", "status": "passed", "attachments": [{"name": "Хоп 1 детали", "source": "68137106-8031-415b-be49-d740989d6739-attachment.attach"}], "start": 1755742103195, "stop": 1755742103210}, {"name": "Хоп 2", "status": "passed", "attachments": [{"name": "Хоп 2 детали", "source": "210e9b41-d5d7-415a-ae01-5f6f8400c017-attachment.attach"}], "start": 1755742103210, "stop": 1755742103229}], "attachments": [{"name": "Результат", "source": "405836e5-5fe6-4997-8dd2-4929d7e4ea1c-attachment.attach"}], "parameters": [{"name": "dst_ip", "value": "'192.168.43.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755742103195, "stop": 1755742103229}], "start": 1755742103195, "stop": 1755742103229}, {"name": "Проверка достижения цели", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.43.2 не достигнута\nassert False\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 130, in test_traceroute_to_ce\n    assert reached_destination, f\"Цель {ce_ip} не достигнута\"\n"}, "start": 1755742103229, "stop": 1755742103229}], "parameters": [{"name": "ce_ip", "value": "'192.168.43.2'"}], "start": 1755742103195, "stop": 1755742103230, "uuid": "e2e56d7c-42b5-4113-ad80-4f9a72ea8465", "historyId": "2299e8c537bf1def73fd98e543964c15", "testCaseId": "430986e6801dc82aa72d8850714fa921", "fullName": "test_traceroute#test_traceroute_to_ce", "labels": [{"name": "epic", "value": "Сетевые тесты"}, {"name": "feature", "value": "Traceroute тестирование"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "7368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}