{"name": "Traceroute к 192.168.43.2", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.43.2 не достигнута\nassert False", "trace": "ce_ip = '192.168.43.2'\n\n    @allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Traceroute тестирование\")\n    @allure.title(\"Traceroute к CE устройствам\")\n    @allure.description(\"Тестирование маршрута до CE устройств через VLAN\")\n    @pytest.mark.parametrize(\"ce_ip\", IP_DST)\n    def test_traceroute_to_ce(ce_ip):\n    \n        allure.dynamic.title(f\"Traceroute к {ce_ip}\")\n        allure.dynamic.description(f\"Проверка маршрута до устройства {ce_ip}\")\n    \n        with allure.step(\"Запуск traceroute\"):\n            hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n    \n        # Проверка достижения цели\n        with allure.step(\"Проверка достижения цели\"):\n>           assert reached_destination, f\"Цель {ce_ip} не достигнута\"\nE           AssertionError: Цель 192.168.43.2 не достигнута\nE           assert False\n\ntest_traceroute.py:128: AssertionError"}, "description": "Проверка маршрута до устройства 192.168.43.2", "steps": [{"name": "Запуск traceroute", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.43.2'", "status": "passed", "steps": [{"name": "Traceroute к 192.168.43.2", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "8ea59138-e341-4f5c-b3e4-9db72c17c070-attachment.attach"}], "start": 1755750176239, "stop": 1755750176240}, {"name": "Хоп 1", "status": "passed", "attachments": [{"name": "Хоп 1 детали", "source": "ebc69d5e-1a84-4d11-91c1-090abc9b822d-attachment.attach"}], "start": 1755750176240, "stop": 1755750176258}, {"name": "Хоп 2", "status": "passed", "attachments": [{"name": "Хоп 2 детали", "source": "2e01caf1-ad00-43e3-bc22-36bc60db5ec1-attachment.attach"}], "start": 1755750176258, "stop": 1755750176282}], "parameters": [{"name": "dst_ip", "value": "'192.168.43.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755750176239, "stop": 1755750176282}], "start": 1755750176239, "stop": 1755750176282}, {"name": "Проверка достижения цели", "status": "failed", "statusDetails": {"message": "AssertionError: Цель 192.168.43.2 не достигнута\nassert False\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 128, in test_traceroute_to_ce\n    assert reached_destination, f\"Цель {ce_ip} не достигнута\"\n"}, "start": 1755750176282, "stop": 1755750176282}], "parameters": [{"name": "ce_ip", "value": "'192.168.43.2'"}], "start": 1755750176239, "stop": 1755750176283, "uuid": "f361195e-a71f-452b-b042-72f31249ecfe", "historyId": "2299e8c537bf1def73fd98e543964c15", "testCaseId": "430986e6801dc82aa72d8850714fa921", "fullName": "test_traceroute#test_traceroute_to_ce", "labels": [{"name": "feature", "value": "Traceroute тестирование"}, {"name": "epic", "value": "Сетевые тесты"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "20721-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}